import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import "./main.scss";
// import {SupabaseProvider} from "@/app/_providers/supabase-provider";
import {Toaster} from 'react-hot-toast';
import React from "react";
import {DialogProvider} from "@/app/_providers/dialog";
import {AlertDialog} from "@/ui/alert/AlertDialog";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Safaricom SIM Tracker",
    description: "Generated by create next app",
    icons:{
        icon:"/fav.png"
    }
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {/*<SupabaseProvider>*/}
            <DialogProvider>
                {/*<DialogStyles/>*/}
                {children}
            </DialogProvider>
            <Toaster position="bottom-center"/>
        <AlertDialog/>
        {/*</SupabaseProvider>*/}
        </body>
        </html>
    );
}
